/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logico.LeerFile;
import Logico.Registro;
import Logico.Servidor;
import Logico.hiloServer;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.When;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alcarmon
 */
public class srvVista extends javax.swing.JFrame {

    
    
Servidor servidor;
LeerFile filtro;
DefaultTableModel ModeloTable=new DefaultTableModel();
DefaultTableModel MdltblFiltro=new DefaultTableModel();
DefaultTableModel mdlped=new DefaultTableModel();
DefaultTableModel mdlve=new DefaultTableModel();

int[]vldsuc=new int[3];
int[]vldped=new int[3];
String [] cons= new String [3];
String [] consp=new String[3];
static ImageIcon icono;


    /**
     * Creates new form srvVista
     * @throws java.io.IOException
     */
    public srvVista() throws IOException {
        initComponents();
        mdlped.addColumn("Código Ciudad");
        mdlped.addColumn("Ciudad");
        mdlped.addColumn("Cantidad Pedidos");

        mdlve.addColumn("Código Ciudad");
        mdlve.addColumn("Ciudad");
        mdlve.addColumn("Ventas");

        servidor=new Servidor(EPEstado, ModeloTable);
        Thread hilo = new Thread(servidor);
        hilo.start(); 
        chkFBogota.setSelected(rootPaneCheckingEnabled);
        chkFMedellin.setSelected(rootPaneCheckingEnabled);
        chkfCartagena.setSelected(rootPaneCheckingEnabled);
        chkDomicilio.setSelected(rootPaneCheckingEnabled);
        chkmesa.setSelected(rootPaneCheckingEnabled);
        chkLlevar.setSelected(rootPaneCheckingEnabled);
        chkCPBogota.setSelected(rootPaneCheckingEnabled);
        chkCPMedellin.setSelected(rootPaneCheckingEnabled);
        chkCPCartagena.setSelected(rootPaneCheckingEnabled);
        chkCVBogota.setSelected(rootPaneCheckingEnabled);
        chkCVMedellin.setSelected(rootPaneCheckingEnabled);
        chkCVCartagena1.setSelected(rootPaneCheckingEnabled);
    }
public void reiniciarJTable(javax.swing.JTable Tabla) throws IOException{
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);

 
//        TableColumnModel modCol = Tabla.getColumnModel(); ***Estas dos lineas limpian el nombre de las columnas de la tab
//        while(modCol.getColumnCount()>0)modCol.removeColumn(modCol.getColumn(0));
    }
    public void verchkbx() throws IOException{
        
        if(chkFBogota.isSelected()==true){
            vldsuc[0]=1;
        }
        else{
            vldsuc[0]=0;
        }
            
       if(chkFMedellin.isSelected()==true){
            vldsuc[1]=1;
        }        
       else{
            vldsuc[1]=0;
        }

       if(chkfCartagena.isSelected()==true){
            vldsuc[2]=1;
        }        
       else{
            vldsuc[2]=0;
        }
       if (chkDomicilio.isSelected()==true){
           vldped[0]=1;
       }
       else{
           vldped[0]=0;
       }
       if (chkLlevar.isSelected()==true){
           vldped[1]=1;
       }
       else{
           vldped[1]=0;
       }
       if (chkmesa.isSelected()==true){
           vldped[2]=1;
       }
       else{
           vldped[2]=0;
       }

        filtro=new LeerFile(vldsuc, vldped);
        filtro.filtro();
        tblfiltro.setModel(filtro.getMdlTFtro());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EPEstado = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblREgistro = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblfiltro = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        chkFBogota = new javax.swing.JCheckBox();
        chkfCartagena = new javax.swing.JCheckBox();
        chkFMedellin = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        chkDomicilio = new javax.swing.JCheckBox();
        chkLlevar = new javax.swing.JCheckBox();
        chkmesa = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        chkCVBogota = new javax.swing.JCheckBox();
        chkCVMedellin = new javax.swing.JCheckBox();
        chkCVCartagena1 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        lblCPed = new javax.swing.JLabel();
        txtVen = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCVent = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        chkCPBogota = new javax.swing.JCheckBox();
        chkCPMedellin = new javax.swing.JCheckBox();
        chkCPCartagena = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        lblCPed1 = new javax.swing.JLabel();
        txtPed = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCped = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burguer Gold - Servidor de transacciones");
        setIconImages(null);
        setName("srvGB"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jScrollPane2.setViewportView(EPEstado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eventos", jPanel2);

        tblREgistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblREgistro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registros", jPanel3);

        tblfiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblfiltro);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudades"));

        chkFBogota.setText("Bogotá");
        chkFBogota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFBogotaItemStateChanged(evt);
            }
        });

        chkfCartagena.setText("Cartagena");
        chkfCartagena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkfCartagenaItemStateChanged(evt);
            }
        });

        chkFMedellin.setText("Medellín");
        chkFMedellin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFMedellinItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(chkFBogota)
                .addGap(194, 194, 194)
                .addComponent(chkFMedellin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkfCartagena)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFBogota)
                    .addComponent(chkfCartagena)
                    .addComponent(chkFMedellin))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de pedido"));

        chkDomicilio.setText("A Domicilio");
        chkDomicilio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDomicilioItemStateChanged(evt);
            }
        });

        chkLlevar.setText("Para llevar");
        chkLlevar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkLlevarItemStateChanged(evt);
            }
        });

        chkmesa.setText("A la mesa");
        chkmesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkmesaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(chkDomicilio)
                .addGap(171, 171, 171)
                .addComponent(chkLlevar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(chkmesa)
                .addGap(58, 58, 58))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDomicilio)
                    .addComponent(chkLlevar)
                    .addComponent(chkmesa))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Filtrar registros", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        chkCVBogota.setText("Bogotá");
        chkCVBogota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCVBogotaItemStateChanged(evt);
            }
        });

        chkCVMedellin.setText("Medellín");
        chkCVMedellin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCVMedellinItemStateChanged(evt);
            }
        });

        chkCVCartagena1.setText("Cartagena");
        chkCVCartagena1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCVCartagena1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chkCVBogota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(chkCVMedellin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(chkCVCartagena1)
                .addGap(28, 28, 28))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCVBogota)
                    .addComponent(chkCVMedellin)
                    .addComponent(chkCVCartagena1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCPed.setText("Total Ventas:");

        txtVen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVen.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPed, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtVen)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPed)
                    .addComponent(txtVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblCVent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblCVent);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        chkCPBogota.setText("Bogotá");
        chkCPBogota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCPBogotaItemStateChanged(evt);
            }
        });

        chkCPMedellin.setText("Medellín");
        chkCPMedellin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCPMedellinItemStateChanged(evt);
            }
        });

        chkCPCartagena.setText("Cartagena");
        chkCPCartagena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCPCartagenaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chkCPBogota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(chkCPMedellin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(chkCPCartagena)
                .addGap(28, 28, 28))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCPBogota)
                    .addComponent(chkCPMedellin)
                    .addComponent(chkCPCartagena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCPed1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCPed1.setText("Cantidad total de pedidos:");

        txtPed.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPed.setEnabled(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPed1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtPed)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPed1)
                    .addComponent(txtPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblCped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblCped);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 502, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Consultas", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BURGUER GOLD - SERVIDOR DE TRANSACCIONES");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void consultasped(String []b) throws IOException{
    reiniciarJTable(tblCped);
    filtro.consultas();
    if ("1".equals(b[0])){
        mdlped.addRow(new Object[]{"1","Bogotá",filtro.getContpb()});
    }
    if ("1".equals(b[1])){
        mdlped.addRow(new Object[]{"2","Medellín",filtro.getContpm()});
    }
    if ("1".equals(b[2])){
        mdlped.addRow(new Object[]{"3","Cartagena",filtro.getContpc()});
    }
    tblCped.setModel(mdlped);
    txtPed.setText(String.valueOf(filtro.getContlinea()));

    
}

public void consultasven(String[] a) throws IOException{
    reiniciarJTable(tblCVent);
    filtro.consultas();
    if ("1".equals(a[0])){
        mdlve.addRow(new Object[]{"1","Bogotá",filtro.getVenb()});
    }
    if ("1".equals(a[1])){
        mdlve.addRow(new Object[]{"2","Medellín",filtro.getVenm()});
    }
    if ("1".equals(a[2])){
        mdlve.addRow(new Object[]{"3","Cartagena",filtro.getVenc()});
    }
    tblCVent.setModel(mdlve);
    txtVen.setText(String.valueOf(filtro.getTotalventas()));

}

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ModeloTable.addColumn("Cod. ciudad");
        ModeloTable.addColumn("Ciudad");
        ModeloTable.addColumn("Cod. pedido");
        ModeloTable.addColumn("Tipo pedido");
        ModeloTable.addColumn("Valor Total");
        tblREgistro.setModel(ModeloTable);

        


        
    }//GEN-LAST:event_formWindowOpened

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    try {
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void chkFBogotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFBogotaItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_chkFBogotaItemStateChanged

    private void chkFMedellinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFMedellinItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkFMedellinItemStateChanged

    private void chkfCartagenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkfCartagenaItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkfCartagenaItemStateChanged

    private void chkDomicilioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDomicilioItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkDomicilioItemStateChanged

    private void chkLlevarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkLlevarItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkLlevarItemStateChanged

    private void chkmesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkmesaItemStateChanged
    try {
        reiniciarJTable(tblfiltro);
        verchkbx();
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkmesaItemStateChanged

    private void chkCVBogotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCVBogotaItemStateChanged
    try {
        if (chkCVBogota.isSelected()==true){
            cons[0]="1";
        }
        else
        {
            cons[0]="0";
        }
        if (chkCVMedellin.isSelected()==true){
            cons[1]="1";
        }
        else
        {
            cons[1]="0";

        }
        if (chkCVCartagena1.isSelected()==true){
            cons[2]="1";
        }
        else
        {
            cons[2]="0";
        }
        consultasven(cons);
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkCVBogotaItemStateChanged

    private void chkCVMedellinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCVMedellinItemStateChanged
    try {
        if (chkCVBogota.isSelected()==true){
            cons[0]="1";
        }
        else
        {
            cons[0]="0";
        }
        if (chkCVMedellin.isSelected()==true){
            cons[1]="1";
        }
        else
        {
            cons[1]="0";

        }
        if (chkCVCartagena1.isSelected()==true){
            cons[2]="1";
        }
        else
        {
            cons[2]="0";
        }
        consultasven(cons);
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkCVMedellinItemStateChanged

    private void chkCVCartagena1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCVCartagena1ItemStateChanged
    try {
        if (chkCVBogota.isSelected()==true){
            cons[0]="1";
        }
        else
        {
            cons[0]="0";
        }
        if (chkCVMedellin.isSelected()==true){
            cons[1]="1";
        }
        else
        {
            cons[1]="0";

        }
        if (chkCVCartagena1.isSelected()==true){
            cons[2]="1";
        }
        else
        {
            cons[2]="0";
        }
        consultasven(cons);
    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkCVCartagena1ItemStateChanged

    private void chkCPBogotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCPBogotaItemStateChanged
    try {
        if (chkCPBogota.isSelected()==true){
            consp[0]="1";
        }
        else
        {
            consp[0]="0";
        }
        if (chkCPMedellin.isSelected()==true){
            consp[1]="1";
        }
        else
        {
            consp[1]="0";

        }
        if (chkCPCartagena.isSelected()==true){
            consp[2]="1";
        }
        else
        {
            consp[2]="0";
        }
        consultasped(consp);
    } 
    catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_chkCPBogotaItemStateChanged

    private void chkCPMedellinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCPMedellinItemStateChanged
    try {
        if (chkCPBogota.isSelected()==true){
            consp[0]="1";
        }
        else
        {
            consp[0]="0";
        }
        if (chkCPMedellin.isSelected()==true){
            consp[1]="1";
        }
        else
        {
            consp[1]="0";

        }
        if (chkCPCartagena.isSelected()==true){
            consp[2]="1";
        }
        else
        {
            consp[2]="0";
        }
        consultasped(consp);    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_chkCPMedellinItemStateChanged

    private void chkCPCartagenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCPCartagenaItemStateChanged
    try {
        if (chkCPBogota.isSelected()==true){
            consp[0]="1";
        }
        else
        {
            consp[0]="0";
        }
        if (chkCPMedellin.isSelected()==true){
            consp[1]="1";
        }
        else
        {
            consp[1]="0";

        }
        if (chkCPCartagena.isSelected()==true){
            consp[2]="1";
        }
        else
        {
            consp[2]="0";
        }
        consultasped(consp);    } catch (IOException ex) {
        Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_chkCPCartagenaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(srvVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(srvVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(srvVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(srvVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new srvVista().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(srvVista.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane EPEstado;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JCheckBox chkCPBogota;
    private javax.swing.JCheckBox chkCPCartagena;
    private javax.swing.JCheckBox chkCPMedellin;
    private javax.swing.JCheckBox chkCVBogota;
    private javax.swing.JCheckBox chkCVCartagena1;
    private javax.swing.JCheckBox chkCVMedellin;
    private javax.swing.JCheckBox chkDomicilio;
    private javax.swing.JCheckBox chkFBogota;
    private javax.swing.JCheckBox chkFMedellin;
    private javax.swing.JCheckBox chkLlevar;
    private javax.swing.JCheckBox chkfCartagena;
    private javax.swing.JCheckBox chkmesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCPed;
    private javax.swing.JLabel lblCPed1;
    private javax.swing.JTable tblCVent;
    private javax.swing.JTable tblCped;
    private javax.swing.JTable tblREgistro;
    private javax.swing.JTable tblfiltro;
    private javax.swing.JTextField txtPed;
    private javax.swing.JTextField txtVen;
    // End of variables declaration//GEN-END:variables

}
